# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-04 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0002_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
